sudo: required
services:
  - docker
language: node_js
node_js:
- '6.1'
cache: yarn

jobs:
  include:
    - script: yarn test
    - stage: Build Static Assets
      script: yarn run build
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: react-ssr-docker
        skip_cleanup: true
        local_dir: deploy
    - stage: Build Docker Image
      deploy:
        script: scripts/build.sh
        on:
          branch: master
