sudo: required
services:
  - docker
language: node_js
node_js:
- '6.1'
cache: yarn

jobs:
  include:
    - script: yarn test
    - stage: Build Static Assets
      script: yarn run build
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_ID
        secret_access_key: $AWS_ACCESS_KEY
        bucket: react-ssr-docker
        skip_cleanup: true
        local_dir: deploy
    - stage: Build Docker Image
      script: scripts/build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "AWS"" -p "$AWS_DOCKER_PASSWORD"" -e none https://396984747102.dkr.ecr.us-west-2.amazonaws.com
    docker push 396984747102.dkr.ecr.us-west-2.amazonaws.com/react-ssr-docker:latest
    fi
